### ISSUE TITLE
Changing `roleMappings` leads to replacements but should not

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-eks#46] opened 2019-01-17 06:15 UTC
A [user on slack](https://pulumi-community.slack.com/archives/C84L4E3N1/p1547657437489600) reported that changes to `roleMappings` lead to repalcements of Kubernetes resources.  It is important that this be possible without replacement, and there is no fundmanetal reason this should require replacement at the EKS/Kubernetes layer.

> Updated the `roleMappings` with a new mapping and, run preview: 

```
❯ pulumi preview
Previewing update (org/eks-name):

    Type                                                           Name                     Plan        Info
    pulumi:pulumi:Stack                                            eks-eks-name
>-  ├─ pulumi:pulumi:StackReference                                identityStack            read
    ├─ kubernetes:helm.sh:Chart                                    kube-state-metrics
+-  │  ├─ kubernetes:extensions:Deployment                         kube-state-metrics       replace     [diff: ~provider]
+-  │  ├─ kubernetes:core:Service                                  kube-state-metrics       replace     [diff: ~provider]
+-  │  ├─ kubernetes:rbac.authorization.k8s.io:ClusterRole         kube-state-metrics       replace     [diff: ~provider]
+-  │  ├─ kubernetes:rbac.authorization.k8s.io:ClusterRoleBinding  kube-state-metrics       replace     [diff: ~provider]
+-  │  └─ kubernetes:core:ServiceAccount                           kube-state-metrics       replace     [diff: ~provider]
+-  ├─ kubernetes:core:Namespace                                   dev                      replace     [diff: ~provider]
    └─ eks:index:Cluster                                           cluster
+-     ├─ pulumi:providers:kubernetes                              cluster-provider         replace     [diff: ~kubeconfig]
+-     ├─ aws:cloudformation:Stack                                 cluster-nodes            replace
+-     └─ kubernetes:core:ConfigMap                                cluster-nodeAccess       replace     [diff: ~data]

Resources:
   +-9 to replace
   24 unchanged
```

**Comment by pgavlin** [comment] 2019-01-17 06:35
The issue occurs due to the interaction of several factors:
- The CFN stack created by the cluster explicitly depends on the config map that manages role mappings. This is done so that worker nodes can connect to the k8s cluster as soon as they come up. I do not think that it is a hard requirement.
- The k8s provider exported by the cluster depends on the CFN stack so that no deployments are attempted with that provider until the worker nodes have come up and connected to the cluster. Again, probably not strictly necessary.
- A change to a resource’s provider forces the recreation of the resource itself.
- Our k8s provider always recreates config maps if they change. This is an intentional decision.
- The k8s config map in question is explicitly named, and therefore must be deleted before its replacement is created.
- Our DBR semantics currently force _all transitive dependents_ of the resource to be promptly deleted (and later recreated).

Taken together, the change to the role mappings causes the `aws-auth` config map to be DBR’d, which causes the provider that transitively depends on it to be replaced, which causes all downstream resources to be replaced.

I can see a short-term workaround and a long-term fix:
1. Do not mix the config map in as a dependency of the CF stack, and do not mix the CF stack in as a dependency of the EKS cluster’s exported k8s provider. This takes care of the immediate issue.
2. Fix the DBR semantics: https://github.com/pulumi/pulumi/issues/2167

**Comment by naveensrinivasan** [comment] 2019-01-17 16:22
When is this likely to be fixed either short term/long term?

Thanks

**Comment by casey-robertson** [comment] 2019-01-18 16:18
@lukehoban if it's better form, I'll start opening issues here unless it's still ok to chat about it on Slack first.  Often times it's my misunderstanding and I don't want to clutter your issues.  Thanks for the attention!

**Comment by lukehoban** [comment] 2019-01-18 16:46
@casey-robertson either is fine, but issues here are useful for tracking and broader awareness. 

@naveensrinivasan we are working on a fix for https://github.com/pulumi/pulumi/issues/2167 now which would address the underlying issue here. You can track details on that on that issue.

**Comment by pgavlin** [comment] 2019-01-31 23:17
This will be resolved with the next update of this package's dependency on `@pulumi/pulumi`, which contains a fix for the root cause.

**Closed** 2019-03-01 00:05 UTC
