### ISSUE TITLE
TestAccNetworkPolicies flake

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-eks#1537] opened 2024-12-17 16:28 UTC
From https://github.com/pulumi/pulumi-eks/issues/1531

```
FAIL: TestAccNetworkPolicies (2058.42s)

        	Error:      	Not equal:
        	            	expected: 7
        	            	actual  : 6
        	Test:       	TestAccNetworkPolicies
        	Messages:   	6 out of 7 Pods are ready

```

**Comment by flostadler** [comment] 2024-12-18 14:27
This is a duplicate of https://github.com/pulumi/pulumi-eks/issues/1465
Closing in favor of the other one

**Closed by flostadler** 2024-12-18 14:27 UTC
Labels: resolution/duplicate, kind/engineering, impact/flaky-test
