### ISSUE TITLE
Creating Configmap via Pulumi throws an invalid apiversion error

### ISSUE THREAD

**Issue by siddhubp** [pulumi/pulumi-eks#740] opened 2022-07-18 19:33 UTC
### What happened?

a simple test pulumi code to create a configmap in (EKS) Kubernetes 1.22 version. I am creating a list

```const ext_secrets_testGame_configConfigMap = new kubernetes.core.v1.ConfigMap("ext_secrets_testGame_configConfigMap", {
    apiVersion: "v1",
    kind: "ConfigMap",
    metadata: {
        name: "game-config",
        namespace: "default",
    },
    data: {
        "game.properties": `enemies=aliens
    lives=3
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
    secret.code.passphrase=UUDDLRLRBABAS
    secret.code.allowed=true
    secret.code.lives=30
`,
        "ui.properties": `color.good=purple
    color.bad=yellow
    allow.textmode=true
    how.nice.to.look=fairlyNice
`,
    },
});
```

causes error

error: failed to initialize discovery client: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

### Steps to reproduce
Creating a configmap using YAML file works fine  in the default (or any other) namespace, however, same YAML code converted to pulumi typescript (using kube2pulumi or manually converted) and used to create a configmap using Pulumi by executing "pulumi up" produces the error mentioned below.

Pulumi version - v3.36.0

### Expected Behavior

Config map to be created without any issue

### Actual Behavior

Previewing update (ngsdl-content-common):
     Type                             Name                                  Plan       Info
 +   pulumi:pulumi:Stack              common-XXXXXX-XXXXXXX-common           create     
     └─ kubernetes:core/v1:ConfigMap  ext_secrets_testGame_configConfigMap             1 error
 
Diagnostics:
  kubernetes:core/v1:ConfigMap (ext_secrets_testGame_configConfigMap):
    error: failed to initialize discovery client: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

### Versions used

pulumi about                                                                                                                                                                
CLI          
Version      3.36.0
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.10.0
docker      3.2.0
kubernetes  3.20.0
nodejs      unknown

Host     
OS       darwin
Version  10.14.6
Arch     x86_64

This project is written in nodejs: executable='/Users/XXXXXXXX/.asdf/shims/node' version='v12.16.3'

Backend        
Name           XXXXXXXXXXXXXXX
URL            s3://XXXXXXXXXXXXXXXX
User           XXXXXXX
Organizations  

Dependencies:
NAME                VERSION
@pulumi/aws         5.10.0
@pulumi/awsx        0.40.0
@pulumi/kubernetes  3.20.0
@pulumi/pulumi      3.36.0
@types/node         14.18.22

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by siddhubp** [comment] 2022-07-18 20:23
I did find a work around to make it work. https://stackoverflow.com/questions/72126048/circleci-message-error-exec-plugin-invalid-apiversion-client-authentication
I manually changed the APIVERSION from v1alpha1 to v1beta1 in my kubeconfig to fix the issue but its kind of interesting, that creating configmap works with YAML file while using v1alpha1 but with pulumi it does not.

**Comment by viveklak** [comment] 2022-07-18 20:36
Closing duplicate of https://github.com/pulumi/pulumi-eks/issues/717

**Closed by viveklak** 2022-07-18 20:36 UTC
Labels: resolution/duplicate, kind/bug
