### ISSUE TITLE
Use new kubectlReplace Invoke function

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-eks#160] opened 2019-06-12 19:14 UTC
With https://github.com/pulumi/pulumi-kubernetes/pull/579 merged, to close out https://github.com/pulumi/pulumi-eks/issues/65, we should replace the current `kubectl apply` Invoke with the new `kubectlReplace` invoke function added in the kube provider.

ref: https://github.com/pulumi/pulumi-kubernetes/issues/509

**Comment by metral** [comment] 2019-06-26 23:15
We've been hitting #65 a good amount this week. Are there any updates to share?

**Comment by lukehoban** [comment] 2019-07-03 13:54
After some attempts to use this - it appears that in its current form we likely can't use the new `kubectlReplace` invoke.  I'm going to close this out, and we'll continue to track the actual user-facing requirement in #65.

Raw notes:

1. We cannot use `invoke` inside a dynamic provider.
2. We should not have to use a dynamic provider - and in fact life would be cleaner if we didn't.  But not using one will mean the action gets taken on every deployment, not just when there are changes, so it must ensure that it is a noop when there are not changes.
3. Replace is almost certainly not going to work in general (it has downtime), but in particular won't work if this has to be outside a dynamic provider since it is not a noop with no changes (it has downtime).
4. It is not 100% clear that even doing any of the above will fix the problem here (#65) - it does not seem we have yet root caused the problem itself (is it that EKS tells us it's done before the control plane is responsive?)
5. We probably need to do some cheaper immediate fix - like a sleep or a light healthcheck
6. We probably also need to do a real `apply` invoke that actually solves for this scenario (and others) in the Kubernetes provider

**Closed by lukehoban** 2019-07-03 13:54 UTC
Labels: priority/p1
