### ISSUE TITLE
Support for EKS Auto Mode

### ISSUE THREAD

**Issue by jhamman** [pulumi/pulumi-eks#1509] opened 2024-12-02 18:56 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

AWS EKS has recently added a new "Auto Mode" feature: https://aws.amazon.com/blogs/aws/streamline-kubernetes-cluster-management-with-new-amazon-eks-auto-mode/. We would like to try this feature in our Pulumi-managed EKS cluster. 

Specific questions:
1. How can I create a new cluster with this mode enabled?
2. can I upgrade an existing cluster to use this mode?

**Comment by flostadler** [comment] 2024-12-03 09:01
Hey @jhamman, thanks a lot for this feature request!

In order to support this new feature we'll first need it to be supported in the upstream terraform provider. Good news is that the [PR](https://github.com/hashicorp/terraform-provider-aws/issues/40373) for this has already been merged and seems to be queued up for the next release. Once that's released, it'll get pulled into `pulumi-aws` shortly after.
After that we can start the work on adding support for this in `pulumi-eks`.


To answer your second question, according to AWS docs it seems like you can enable auto mode on existing clusters and migrate workloads safely: https://docs.aws.amazon.com/eks/latest/userguide/migrate-auto.html.

**Comment by flostadler** [comment] 2024-12-03 09:16
Depends on: https://github.com/pulumi/pulumi-aws/issues/4873

**Comment by flostadler** [comment] 2024-12-04 16:12
Support for this landed in `pulumi-aws` just now. I'm working on adding support for it to pulumi-eks now

**Comment by flostadler** [comment] 2024-12-05 11:55
While implementing this I found a bug in the implementation of `aws.eks.Cluster` that prevents updating an existing cluster to use EKS Auto Mode: https://github.com/pulumi/pulumi-aws/issues/4885

This bug is in turn caused by the following upstream bug: https://github.com/hashicorp/terraform-provider-aws/issues/40411
I'm investigating what options we have to work around this

**Closed** 2024-12-16 13:59 UTC
Labels: kind/enhancement
