### ISSUE TITLE
pulumi-eks: referencing cluster.id does not return a value

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-eks#551] opened 2021-03-08 19:06 UTC
I have a cluster declaration in python as follows:
```
cluster = Cluster(
    f"{proj_name}-eks",
    fargate=FargateProfileArgs(selectors=[
        FargateProfileSelectorArgs(namespace=app_namespace_name),
        FargateProfileSelectorArgs(namespace=sys_namespace_name),
        FargateProfileSelectorArgs(namespace=alb_controller_namespace_name),
    ]),
    vpc_id=vpc_id,
    private_subnet_ids = priv_subnet_ids,
    create_oidc_provider=True,
    version="1.19",
)
```

If I try to reference `cluster.id` it does not return any value. 
Using `cluster.id.apply()` throws an error that cluster.id does not support apply().

`cluster.core.clsuter.id` does return the expected value.

## Expected behavior

`cluster.id` should return a value as per the documentation. 
Or the documentation should be updated to remove the "id" output property.

## Current behavior
See above.

## Steps to reproduce

1. Create an eks cluster use the eks extension package.
2. Try to access "cluster.id" 
3.
4.

## Context (Environment)

Either the documentation is wrong or the the provider should return `cluster.id`
The fact that `cluster.core.cluster.id` works means this is not a critical issue.

**Comment by lukehoban** [comment] 2021-03-08 19:23
> If I try to reference cluster.id it does not return any value.

That's right - there is no `id` property on `eks.Cluster` (or in general, on any `ComponentResource`).

> Either the documentation is wrong or the the provider should return cluster.id

Which documentation suggested this?  It does sound like that documentation is wrong.

**Comment by stack72** [comment] 2022-07-27 13:43
I am going to close this out - I can't find any instance where there are `cluster.id` references in our registry. If you can point to a specific place then we can try and fix that up to

**Comment by MitchellGerdisch** [comment] 2022-07-27 13:59
Sorry - I should have added the docs reference originally.
The pulumi-eks package docs show an `id` Output:
https://www.pulumi.com/registry/packages/eks/api-docs/cluster/#outputs

**Comment by stack72** [comment] 2022-07-27 21:25
Thanks @MitchellGerdisch - I will file this as a bug

**Comment by danielrbradley** [comment] 2022-11-23 20:15
This is a documentation generation issue. I've filed this as a separate bug on that side.

Closing as a duplicate of https://github.com/pulumi/docs/issues/8268

**Closed by danielrbradley** 2022-11-23 20:15 UTC
Labels: resolution/duplicate, kind/bug, 1.0
