### ISSUE TITLE
VPC CNI should be not installed if useDefaultVpcCni is set to False

### ISSUE THREAD

**Issue by blakeromano** [pulumi/pulumi-eks#905] opened 2023-08-23 00:56 UTC
### What happened?

I want to use the Cilium CNI and not the VPC CNI and the VPC CNI should not be installed as apart of the Cluster Resource

### Expected Behavior

I'd expect if I specify
```
useDefaultVpcCni: false
```

That the EKS Cluster would not spin up with the VPC CNI.

### Steps to reproduce

```
new eks.Cluster("cluster", {
      name: "cluster",
      useDefaultVpcCni: false,
      createOidcProvider: true,
    })
```

### Output of `pulumi about`

```
CLI          
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.42.0
aws         5.31.0
aws-native  0.73.0
awsx        1.0.2
docker      3.6.1
eks         1.0.2
github      5.15.0
kubernetes  3.30.2
nodejs      unknown

Host     
OS       darwin
Version  13.4
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v20.3.1'

Backend        
Name           pulumi.com
URL            IGNORE
User           IGNORE
Organizations  IGNORE

Dependencies:
NAME                VERSION
@pulumi/aws         5.42.0
@pulumi/aws-native  0.73.0
@pulumi/awsx        1.0.2
@pulumi/eks         1.0.2
@pulumi/github      5.15.0
@pulumi/pulumi      3.76.1
@types/js-yaml      4.0.5
js-yaml             4.1.0
@types/node         16.18.39
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment] 2023-08-24 14:02
Hi @blakeromano thanks for writing this up.

The documentation for the `useDefaultVpcCni` says
> Use the default VPC CNI instead of creating a custom one. Should not be used in conjunction with vpcCniOptions.

If this is unset or set to `false` then it will create a custom CNI. If this is set to `true` then it will use the CNI from the default VPC instead. I think the issue is that this property doesn't control what you're expecting it to - it doesn't disable using any CNI.

I'm going to close this as by-design as it's not a bug according to how it was implemented. I'd suggest that if you need additional customisability then you could propose a design for the new feature. If the feature isn't widely requested it might be better creating the resources from EKS directly in your program to give you greater control over the inner properties.

**Closed by danielrbradley** 2023-08-24 14:02 UTC
Labels: kind/bug, resolution/by-design
