### ISSUE TITLE
Error using `eks.AuthenticationModeApiAndConfigMap` with cluster created with pulumi-eks v2

### ISSUE THREAD

**Issue by afreakk** [pulumi/pulumi-eks#1476] opened 2024-11-10 10:52 UTC
### What happened?

I'm trying to run something similar to this: https://github.com/pulumi/pulumi-eks/blob/00353a9d5579be4e1b7c227af7753663b6b36a32/examples/cluster-go/step2/main.go#L23
And use on existing cluster, that was created without api-mode authentication.
And have the code as seen below, but I end up getting `waiting for RPCs: expected a eks.AccessEntry, got a resource of type *eks.AccessEntry`
and with some changes I get `waiting for RPCs: marshaling properties: awaiting input property "assumeRolePolicy": expected a eks.AccessEntry, got a resource of type *eks.AccessEntry`.
And I have also seen `awaiting input property "controllerId": expected a eks.AccessEntry, got a resource of type *eks.AccessEntry`, which somehow seems related to the ocean group we make, but I've disabled that until I figure out why I get this error.

An important thing here seems to be, that if i change the name of the cluster, like postfix  some string to the clustername.
`eks.NewCluster(ctx, eksClusterName+"yo", clusterArgs, opts...)`
I no longer get that error, so this is related to having an existing cluster made with pulumi-eks v2

### Example

	authMode := eks.AuthenticationModeApiAndConfigMap
	role, err := iam.NewRole(ctx, "example-cluster-2-role", &iam.RoleArgs{
		AssumeRolePolicy: pulumi.String(`{
				"Version": "2012-10-17",
				"Statement": [{
					"Action": "sts:AssumeRole",
					"Effect": "Allow",
					"Principal": {
						"Service": "ec2.amazonaws.com"
					}
				}]
			}`),
	})
	if err != nil {
		return nil, err
	}
	clusterArgs := &eks.ClusterArgs{
		AuthenticationMode: &authMode,
		AccessEntries: map[string]eks.AccessEntryArgs{
			"example-cluster-role": eks.AccessEntryArgs{
				PrincipalArn: role.Arn,
				AccessPolicies: map[string]eks.AccessPolicyAssociationInput{
					"view": eks.AccessPolicyAssociationArgs{
						PolicyArn: pulumi.String("arn:aws:eks::aws:cluster-access-policy/AmazonEKSViewPolicy"),
						AccessScope: awseks.AccessPolicyAssociationAccessScopeArgs{
							Type: pulumi.String("namespace"),
							Namespaces: pulumi.StringArray{
								pulumi.String("default"),
							},
						},
					},
				},
			},
		},
	}
	return eks.NewCluster(ctx, eksClusterName, clusterArgs, opts...)

### Output of `pulumi about`

CLI
Version      3.134.1
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  aiven         6.1.1
resource  aws           6.29.0
resource  aws           5.43.0
resource  awsx          2.3.0
resource  cloudamqp     3.16.0
resource  command       0.6.0
resource  docker        4.4.4
resource  eks           3.0.0
language  go            unknown
resource  kubernetes    4.9.1
resource  mongodbatlas  3.7.2
resource  mysql         3.1.0
resource  postgresql    3.11.3
resource  rabbitmq      3.3.0
resource  random        4.8.2
resource  spotinst      3.60.0
resource  tailscale     0.11.0
resource  tls           4.6.1

Host
OS       nixos
Version  24.11 (Vicuna)
Arch     x86_64

This project is written in go: executable='/nix/store/yij3vkkjv7ghn055v0rqhbjzyh0dy4nq-go-1.21.13/bin/go' version='go version go1.21.13 linux/amd64'

Current Stack: fiveten/aws-cluster-0-stage/euc2

TYPE                                                 URN
pulumi:pulumi:Stack                                  urn:pulumi:euc2::aws-cluster-0-stage::pulumi:pulumi:Stack::aws-cluster-0-stage-euc2
pulumi:providers:aws                                 urn:pulumi:euc2::aws-cluster-0-stage::pulumi:providers:aws::default_6_29_0
pulumi:providers:pulumi                              urn:pulumi:euc2::aws-cluster-0-stage::pulumi:providers:pulumi::default
fiveten:tenant:TenantRegionStorageComponent          urn:pulumi:euc2::aws-cluster-0-stage::fiveten:tenant:TenantRegionStorageComponent::tenantRegionCluster
fiveten:eksspotcluster:EksSpotClusterComponent       urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent::cluster-0-stage-2
pulumi:pulumi:StackReference                         urn:pulumi:euc2::aws-cluster-0-stage::pulumi:pulumi:StackReference::fiveten/aws-region-0-stage/euc1
pulumi:providers:eks                                 urn:pulumi:euc2::aws-cluster-0-stage::pulumi:providers:eks::default_3_0_0
pulumi:providers:aws                                 urn:pulumi:euc2::aws-cluster-0-stage::pulumi:providers:aws::default_6_45_0
eks:index:Cluster                                    urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster::cluster-0-stage-2-eks-cluster
eks:index:ServiceRole                                urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$eks:index:ServiceRole::cluster-0-stage-2-eks-cluster-eksRole
eks:index:ServiceRole                                urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$eks:index:ServiceRole::cluster-0-stage-2-eks-cluster-instanceRole
aws:ec2/keyPair:KeyPair                              urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$aws:ec2/keyPair:KeyPair::cluster-0-stage-2-eks-cluster-keyPair
aws:ec2/securityGroup:SecurityGroup                  urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$aws:ec2/securityGroup:SecurityGroup::cluster-0-stage-2-eks-cluster-eksClusterSecurityGroup
aws:iam/role:Role                                    urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$eks:index:ServiceRole$aws:iam/role:Role::cluster-0-stage-2-eks-cluster-eksRole-role
aws:iam/role:Role                                    urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$eks:index:ServiceRole$aws:iam/role:Role::cluster-0-stage-2-eks-cluster-instanceRole-role
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::cluster-0-stage-2-eks-cluster-eksRole-4b490823
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::cluster-0-stage-2-eks-cluster-eksClusterInternetEgressRule
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::cluster-0-stage-2-eks-cluster-instanceRole-3eb088f2
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::cluster-0-stage-2-eks-cluster-instanceRole-e1b295bd
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::cluster-0-stage-2-eks-cluster-instanceRole-03516f97
aws:iam/instanceProfile:InstanceProfile              urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$aws:iam/instanceProfile:InstanceProfile::cluster-0-stage-2-eks-cluster-instanceProfile
aws:eks/cluster:Cluster                              urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$aws:eks/cluster:Cluster::cluster-0-stage-2-eks-cluster-eksCluster
pulumi:providers:kubernetes                          urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$pulumi:providers:kubernetes::cluster-0-stage-2-eks-cluster-eks-k8s
aws:iam/openIdConnectProvider:OpenIdConnectProvider  urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$aws:iam/openIdConnectProvider:OpenIdConnectProvider::cluster-0-stage-2-eks-cluster-oidcProvider
aws:ec2/securityGroup:SecurityGroup                  urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$aws:ec2/securityGroup:SecurityGroup::cluster-0-stage-2-eks-cluster-nodeSecurityGroup
kubernetes:core/v1:ConfigMap                         urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$kubernetes:core/v1:ConfigMap::cluster-0-stage-2-eks-cluster-nodeAccess
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::cluster-0-stage-2-eks-cluster-eksClusterIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::cluster-0-stage-2-eks-cluster-eksNodeInternetEgressRule
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::cluster-0-stage-2-eks-cluster-eksNodeIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::cluster-0-stage-2-eks-cluster-eksNodeClusterIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::cluster-0-stage-2-eks-cluster-eksExtApiServerClusterIngressRule
aws:eks/addon:Addon                                  urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$aws:eks/addon:Addon::cluster-0-stage-2-eks-cluster-coredns
eks:index:VpcCniAddon                                urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$eks:index:VpcCniAddon::cluster-0-stage-2-eks-cluster-vpc-cni
aws:eks/addon:Addon                                  urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$aws:eks/addon:Addon::cluster-0-stage-2-eks-cluster-kube-proxy
aws:ec2/launchTemplate:LaunchTemplate                urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$aws:ec2/launchTemplate:LaunchTemplate::cluster-0-stage-2-eks-cluster-launchTemplate
aws:eks/addon:Addon                                  urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$eks:index:VpcCniAddon$aws:eks/addon:Addon::cluster-0-stage-2-eks-cluster-vpc-cni
aws:autoscaling/group:Group                          urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$eks:index:Cluster$aws:autoscaling/group:Group::cluster-0-stage-2-eks-cluster
pulumi:providers:kubernetes                          urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$pulumi:providers:kubernetes::cluster-0-stage-2-k8sProvider
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:euc2::aws-cluster-0-stage::aws:ec2/securityGroupRule:SecurityGroupRule::vpc-to-eks-api
kubernetes:core/v1:Namespace                         urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$kubernetes:core/v1:Namespace::cloudflared
kubernetes:helm.sh/v3:Release                        urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$pulumi:providers:kubernetes$kubernetes:helm.sh/v3:Release::vantage-kubernetes-agent
kubernetes:core/v1:Service                           urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$pulumi:providers:kubernetes$kubernetes:core/v1:Service::tailnet-exposer-signoz-stage-euc-to-signoz-otel-collector-prod
kubernetes:helm.sh/v3:Release                        urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$pulumi:providers:kubernetes$kubernetes:helm.sh/v3:Release::tailscale-operator
kubernetes:helm.sh/v3:Release                        urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$pulumi:providers:kubernetes$kubernetes:helm.sh/v3:Release::cluster-0-stage-2-spotinst-controller
kubernetes:storage.k8s.io/v1:StorageClassPatch       urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$pulumi:providers:kubernetes$kubernetes:storage.k8s.io/v1:StorageClassPatch::gp2
kubernetes:helm.sh/v3:Release                        urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$pulumi:providers:kubernetes$kubernetes:helm.sh/v3:Release::1password-connect
kubernetes:helm.sh/v3:Release                        urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$pulumi:providers:kubernetes$kubernetes:helm.sh/v3:Release::otel-cluster-deployment-collector
kubernetes:helm.sh/v3:Release                        urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$pulumi:providers:kubernetes$kubernetes:helm.sh/v3:Release::otel-trace-collector
kubernetes:helm.sh/v3:Release                        urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$pulumi:providers:kubernetes$kubernetes:helm.sh/v3:Release::opentelemetry-collector
pulumi:providers:spotinst                            urn:pulumi:euc2::aws-cluster-0-stage::pulumi:providers:spotinst::default_3_60_0
kubernetes:core/v1:Secret                            urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$kubernetes:core/v1:Namespace$kubernetes:core/v1:Secret::aws-tenant-0-stage-cloudflared
aws:iam/role:Role                                    urn:pulumi:euc2::aws-cluster-0-stage::aws:iam/role:Role::AmazonEKS_EBS_CSI_DriverRole
spotinst:aws/ocean:Ocean                             urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$spotinst:aws/ocean:Ocean::cluster-0-stage-2-eks-cluster-spotinst-oceanNodeGroup
kubernetes:core/v1:ConfigMap                         urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$kubernetes:core/v1:Namespace$kubernetes:core/v1:Secret$kubernetes:core/v1:ConfigMap::aws-tenant-0-stage-cloudflared
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:euc2::aws-cluster-0-stage::aws:iam/rolePolicyAttachment:RolePolicyAttachment::csi-driver-policy-attachement
aws:eks/addon:Addon                                  urn:pulumi:euc2::aws-cluster-0-stage::aws:eks/addon:Addon::aws-ebs-csi-driver-addon
kubernetes:apps/v1:Deployment                        urn:pulumi:euc2::aws-cluster-0-stage::fiveten:eksspotcluster:EksSpotClusterComponent$kubernetes:core/v1:Namespace$kubernetes:core/v1:Secret$kubernetes:core/v1:ConfigMap$kubernetes:apps/v1:Deployment::aws-tenant-0-stage

Found no pending operations associated with fiveten/euc2

Backend
Name           pulumi.com
URL            https://app.pulumi.com/afreakk
User           afreakk
Organizations  afreakk, fiveten
Token type     personal

Dependencies:
NAME                                          VERSION
github.com/aws/aws-sdk-go                     v1.44.298
github.com/goccy/go-yaml                      v1.9.6
github.com/google/uuid                        v1.6.0
github.com/iancoleman/strcase                 v0.2.0
github.com/pkg/errors                         v0.9.1
github.com/pulumi/pulumi-aiven/sdk/v6         v6.1.1
github.com/pulumi/pulumi-aws/sdk/v5           v5.43.0
github.com/pulumi/pulumi-aws/sdk/v6           v6.29.0
github.com/pulumi/pulumi-awsx/sdk/v2          v2.3.0
github.com/pulumi/pulumi-cloudamqp/sdk/v3     v3.16.0
github.com/pulumi/pulumi-command/sdk          v0.6.0
github.com/pulumi/pulumi-docker/sdk/v4        v4.4.4
github.com/pulumi/pulumi-eks/sdk/v3           v3.0.0
github.com/pulumi/pulumi-kubernetes/sdk/v4    v4.9.1
github.com/pulumi/pulumi-mongodbatlas/sdk/v3  v3.7.2
github.com/pulumi/pulumi-mysql/sdk/v3         v3.1.0
github.com/pulumi/pulumi-postgresql/sdk/v3    v3.11.3
github.com/pulumi/pulumi-rabbitmq/sdk/v3      v3.3.0
github.com/pulumi/pulumi-random/sdk/v4        v4.8.2
github.com/pulumi/pulumi-spotinst/sdk/v3      v3.60.0
github.com/pulumi/pulumi-tailscale/sdk        v0.11.0
github.com/pulumi/pulumi-tls/sdk/v4           v4.6.1
github.com/pulumi/pulumi/sdk/v3               v3.134.1
github.com/sirupsen/logrus                    v1.9.0
github.com/spf13/cobra                        v1.8.0
github.com/stretchr/testify                   v1.9.0
gopkg.in/yaml.v3                              v3.0.1
gorm.io/driver/mysql                          v1.5.2
gorm.io/gorm                                  v1.25.5
inet.af/netaddr                               v0.0.0-20230525184311-b8eac61e914a

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment] 2024-11-11 10:11
Hey @afreakk, I'm sorry you're running into this!

This is caused by returning the wrong type in the provider. The issue is tracked [here](https://github.com/pulumi/pulumi-eks/issues/1435) and we're going to start tackling it in the next days.

I'm going to close this as a duplicate in the meantime, please subscribe to the linked issue to get updates.

**Closed** 2024-11-11 10:11 UTC
Labels: needs-triage, resolution/duplicate, kind/bug
