### ISSUE TITLE
Python: Error: 'dependsOn' was passed a value that was not a Resource

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-eks#481] opened 2020-12-04 15:39 UTC
After successfully deploying the below program, running a subsequent `pulumi preview` appears to hang (https://github.com/pulumi/pulumi-eks/issues/480). Pressing CTRL+C to cancel the preview displays the following error:

```
$ pulumi preview
Previewing update (dev)

     Type                 Name           Plan     Info
     pulumi:pulumi:Stack  clusterex-dev           1 error; 180 messages
 C
Diagnostics:
  pulumi:pulumi:Stack (clusterex-dev):
    unhandled rejection: CONTEXT(1163): resource:example-managed-ng1[aws:eks/nodeGroup:NodeGroup]
    STACK_TRACE:
    Error
        at Object.debuggablePromise (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at Object.registerResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:218:18)
        at new Resource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new NodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/eks/nodeGroup.ts:262:9)
        at createManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:847:23)
        at new ManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:768:26)
        at Object.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/nodegroup.ts:46:31)
        at Provider.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/index.ts:88:24)
        at Server.<anonymous> (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/provider/server.js:286:52)
    unhandled rejection: CONTEXT(1163): resource:example-managed-ng1[aws:eks/nodeGroup:NodeGroup]
    STACK_TRACE:
    Error
        at Object.debuggablePromise (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at Object.registerResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:218:18)
        at new Resource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new NodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/eks/nodeGroup.ts:262:9)
        at createManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:847:23)
        at new ManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:768:26)
        at Object.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/nodegroup.ts:46:31)
        at Provider.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/index.ts:88:24)
        at Server.<anonymous> (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/provider/server.js:286:52)
    unhandled rejection: CONTEXT(1163): resource:example-managed-ng1[aws:eks/nodeGroup:NodeGroup]
    STACK_TRACE:
    Error
        at Object.debuggablePromise (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at Object.registerResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:218:18)
        at new Resource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new NodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/eks/nodeGroup.ts:262:9)
        at createManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:847:23)
        at new ManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:768:26)
        at Object.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/nodegroup.ts:46:31)
        at Provider.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/index.ts:88:24)
        at Server.<anonymous> (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/provider/server.js:286:52)
    unhandled rejection: CONTEXT(1311): resource:example-managed-ng0[aws:eks/nodeGroup:NodeGroup]
    STACK_TRACE:
    Error
        at Object.debuggablePromise (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at Object.registerResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:218:18)
        at new Resource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new NodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/eks/nodeGroup.ts:262:9)
        at createManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:847:23)
        at new ManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:768:26)
        at Object.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/nodegroup.ts:46:31)
        at Provider.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/index.ts:88:24)
        at Server.<anonymous> (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/provider/server.js:286:52)
    unhandled rejection: CONTEXT(1311): resource:example-managed-ng0[aws:eks/nodeGroup:NodeGroup]
    STACK_TRACE:
    Error
        at Object.debuggablePromise (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at Object.registerResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:218:18)
        at new Resource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new NodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/eks/nodeGroup.ts:262:9)
        at createManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:847:23)
        at new ManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:768:26)
        at Object.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/nodegroup.ts:46:31)
        at Provider.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/index.ts:88:24)
        at Server.<anonymous> (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/provider/server.js:286:52)
    unhandled rejection: CONTEXT(1311): resource:example-managed-ng0[aws:eks/nodeGroup:NodeGroup]
    STACK_TRACE:
    Error
        at Object.debuggablePromise (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at Object.registerResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:218:18)
        at new Resource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new NodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/eks/nodeGroup.ts:262:9)
        at createManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:847:23)
        at new ManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:768:26)
        at Object.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/nodegroup.ts:46:31)
        at Provider.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/index.ts:88:24)
        at Server.<anonymous> (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/provider/server.js:286:52)
    unhandled rejection: CONTEXT(1405): resource:example-managed-ng2[aws:eks/nodeGroup:NodeGroup]
    STACK_TRACE:
    Error
        at Object.debuggablePromise (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at Object.registerResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:218:18)
        at new Resource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new NodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/eks/nodeGroup.ts:262:9)
        at createManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:847:23)
        at new ManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:768:26)
        at Object.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/nodegroup.ts:46:31)
        at Provider.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/index.ts:88:24)
        at Server.<anonymous> (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/provider/server.js:286:52)
    unhandled rejection: CONTEXT(1405): resource:example-managed-ng2[aws:eks/nodeGroup:NodeGroup]
    STACK_TRACE:
    Error
        at Object.debuggablePromise (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at Object.registerResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:218:18)
        at new Resource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new NodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/eks/nodeGroup.ts:262:9)
        at createManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:847:23)
        at new ManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:768:26)
        at Object.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/nodegroup.ts:46:31)
        at Provider.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/index.ts:88:24)
        at Server.<anonymous> (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/provider/server.js:286:52)
    unhandled rejection: CONTEXT(1405): resource:example-managed-ng2[aws:eks/nodeGroup:NodeGroup]
    STACK_TRACE:
    Error
        at Object.debuggablePromise (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at Object.registerResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:218:18)
        at new Resource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new NodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/eks/nodeGroup.ts:262:9)
        at createManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:847:23)
        at new ManagedNodeGroup (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:768:26)
        at Object.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/nodegroup.ts:46:31)
        at Provider.construct (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/cmd/provider/index.ts:88:24)
        at Server.<anonymous> (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/provider/server.js:286:52)
 
    Error: 'dependsOn' was passed a value that was not a Resource.
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:505:27
        at Generator.next (<anonymous>)
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:17:12)
        at gatherExplicitDependencies (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:483:12)
        at dependsOn.apply.v (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:497:50)
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:249:35
        at Generator.next (<anonymous>)
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:21:71
    Error: A managed node group cannot be created without first setting its role in the cluster's instanceRoles
        at nodegroupRole.apply.role (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:822:19)
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:249:35
        at Generator.next (<anonymous>)
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:228:12)
        at Promise.all.then (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:182:65)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    Error: 'dependsOn' was passed a value that was not a Resource.
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:505:27
        at Generator.next (<anonymous>)
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:17:12)
        at gatherExplicitDependencies (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:483:12)
        at dependsOn.apply.v (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:497:50)
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:249:35
        at Generator.next (<anonymous>)
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:21:71
    Error: 'dependsOn' was passed a value that was not a Resource.
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:505:27
        at Generator.next (<anonymous>)
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:17:12)
        at gatherExplicitDependencies (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:483:12)
        at dependsOn.apply.v (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/runtime/resource.js:497:50)
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:249:35
        at Generator.next (<anonymous>)
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:21:71
    Error: A managed node group cannot be created without first setting its role in the cluster's instanceRoles
        at nodegroupRole.apply.role (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:822:19)
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:249:35
        at Generator.next (<anonymous>)
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:228:12)
        at Promise.all.then (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:182:65)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    Error: A managed node group cannot be created without first setting its role in the cluster's instanceRoles
        at nodegroupRole.apply.role (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/nodegroup.ts:822:19)
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:249:35
        at Generator.next (<anonymous>)
        at /Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:228:12)
        at Promise.all.then (/Users/user/go/src/github.com/pulumi/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:182:65)
        at process._tickCallback (internal/process/next_tick.js:68:7)
 
    error: preview canceled

```

----

main.py:

```python
import pulumi
import pulumi_aws as aws
import pulumi_eks as eks

import iam

# IAM roles for the node groups.
role0 = iam.create_role("example-role0")
role1 = iam.create_role("example-role1")
role2 = iam.create_role("example-role2")

# Create an EKS cluster.
cluster = eks.Cluster("example-managed-nodegroups",
                      skip_default_node_group=True,
                      instance_roles=[role0, role1, role2])

# Export the cluster's kubeconfig.
pulumi.export("kubeconfig", cluster.kubeconfig)

# Create a simple AWS managed node group using a cluster as input and the
# refactored API.
managed_node_group0 = eks.ManagedNodeGroup("example-managed-ng0",
                                           cluster=cluster.core,
                                           node_role=role0)

# Create a simple AWS managed node group using a cluster as input and the
# initial API.
managed_node_group1 = eks.ManagedNodeGroup("example-managed-ng1",
                                           cluster=cluster.core,
                                           node_group_name="aws-managed-ng1",
                                           node_role_arn=role1.arn,
                                           opts=pulumi.ResourceOptions(parent=cluster))

# Create an explicit AWS managed node group using a cluster as input and the
# initial API.
managed_node_group2 = eks.ManagedNodeGroup("example-managed-ng2",
                                           cluster=cluster.core,
                                           node_group_name="aws-managed-ng2",
                                           node_role_arn=role2.arn,
                                           disk_size=20,
                                           instance_types="t2.medium",
                                           labels={"ondemand": "true"},
                                           tags={"org": "pulumi"},
                                           opts=pulumi.ResourceOptions(parent=cluster))
```

iam.py:

```python
import json
import pulumi_aws as aws

managed_policy_arns = [
    "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy",
    "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy",
    "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly",
]

# Creates a role and attaches the EKS worker node IAM managed policies
def create_role(name: str) -> aws.iam.Role:
    role = aws.iam.Role(name, assume_role_policy=json.dumps({
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "AllowAssumeRole",
                "Effect": "Allow",
                "Principal": {
                    "Service": "ec2.amazonaws.com",
                },
                "Action": "sts:AssumeRole"
            }
        ]
    }))

    for i, policy in enumerate(managed_policy_arns):
        # Create RolePolicyAttachment without returning it.
        rpa = aws.iam.RolePolicyAttachment(f"{name}-policy-{i}",
            policy_arn=policy,
            role=role.id)

    return role
```

**Comment by lukehoban** [comment] 2021-07-28 03:59
Duplicate of https://github.com/pulumi/pulumi/issues/5642.

**Closed by lukehoban** 2021-07-28 03:59 UTC
Labels: area/multi-language-components, kind/bug, resolution/duplicate
