### ISSUE TITLE
Unable to config AWS provider when default provider is disabled

### ISSUE THREAD

**Issue by xiayuhuahxy** [pulumi/pulumi-eks#917] opened 2023-10-01 19:01 UTC
### What happened?

With the default provider disabled in the pulumi.prod.yaml (or similar stack configure yamls), it seems no way to setup the AWS provider for _pulumi_eks_, and the following error becomes inevitable while creating the cluster. Pulumi Exception Error:

`Exception: Default provider for 'eks' disabled. 'eks:index:Cluster' must use an explicit provider.`

For pulumi_eks, _provider_ in _ResourceOptions_ is reserved for specifying the Kubernetes Provider. So even with `opts=pulumi.ResourceOptions(provider=our_provider)`, it does not fix the issue and the explicit AWS provider error mentioned above remains.

### Example

1. Disable the default-provider in pulumi.prod.yaml:
```
config:
  pulumi:disable-default-providers:
    - '*'
```
2. Create the EKS cluster in __main__.py:
```
 eks_control_plane = eks.Cluster(
        eks_control_plane_id,
        name=eks_control_plane_id,
        opts=pulumi.ResourceOptions(provider=our_provider),
    )
```

### Output of `pulumi about`

CLI          
Version      3.86.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.42.0
awsx        1.0.5
docker      3.6.1
eks         1.0.3
kubernetes  3.30.2
python      unknown

Host     
OS       darwin
Version  13.4
Arch     arm64

This project is written in python: executable='/Library/Frameworks/Python.framework/Versions/3.11/bin/python3' version='3.11.4'

Current Stack: botauto/compute/prod

Found no resources associated with prod

Found no pending operations associated with prod

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/***
User           ***
Organizations  ***
Token type     personal

Dependencies:
NAME         VERSION
pip          23.2.1
pulumi-awsx  1.0.5
pulumi-eks   1.0.3
setuptools   68.2.2
wheel        0.41.2

Pulumi locates its logs in /var/folders/fk/***/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment] 2023-10-02 15:26
Hi @xiayuhuahxy You should be able to set the providers via the `providers` (plural) option, as shown in https://www.pulumi.com/docs/concepts/options/providers/

Please let me know if that works for you.

**Comment by xiayuhuahxy** [comment] 2023-10-03 23:37
Hi @mikhailshilkov , sadly it does not work. My code:
```
    kube_provider = kube.Provider("kubeProvider", kubeconfig="./kubeconfig")
    eks_provider = eks.Provider("eks")
    test_cluster = eks.Cluster(
        name=f"test_{cluster_name}",
        ...
       vpc_id=default_vpc.id,
        opts = pulumi.ResourceOptions(providers=[aws_provider, kube_provider]),
    )
```
And the error message:
` Exception: Default provider for 'eks' disabled. 'eks:index:Cluster' must use an explicit provider.`

I also tried with
```
 opts = pulumi.ResourceOptions(provider=eks_provider, providers=[aws_provider, kube_provider]),
```
Same error message.

**Comment by iwahbe** [comment] 2023-10-04 01:06
https://pulumi-community.slack.com/archives/C84L4E3N1/p1696084753860589 indicates that passing the following yields a different error message:
```python
 opts = pulumi.ResourceOptions(provider=eks_provider, providers=[aws_provider, kube_provider]),
```
```
Exception: Invoke: Default provider for 'aws' disabled. 'aws:index/getPartition:getPartition' must use an explicit provider.
```

This indicates that there is a bug in the `pulumi-eks` provider, specifically that we are not passing `parent` to this invoke call.

**Comment by xiayuhuahxy** [comment] 2023-10-05 01:45
I agree. The provider was not propagated to the sub-functions properly.

**Comment by xiayuhuahxy** [comment] 2023-10-11 19:52
Hi @mikhailshilkov, as I have provided the feedback, shall we remove this 'awaiting-feedback' label and put a 'bug' label on it?

**Comment by iwahbe** [comment] 2023-10-11 22:55
Doing some digging, it looks like this is a duplicate of https://github.com/pulumi/pulumi-eks/issues/835, and was fixed by https://github.com/pulumi/pulumi-eks/pull/886. The next version of pulumi-eks will resolve this issue.

**Comment by xiayuhuahxy** [comment] 2023-10-15 00:49
> Doing some digging, it looks like this is a duplicate of #835, and was fixed by #886. The next version of pulumi-eks will resolve this issue.

Do we have an ETA for the next release?

**Comment by iwahbe** [comment] 2023-10-17 17:41
https://github.com/pulumi/pulumi-eks/releases/tag/v1.0.4 shouldn't have this bug. 

Please open a new issue if you hit this.

**Closed by iwahbe** 2023-10-17 17:41 UTC
Labels: resolution/duplicate, kind/bug

**Comment by ami-descope** [comment] 2024-08-05 21:32
still happing 

error: Default provider for 'eks' disabled. 'urn:pulumi:sandbox::aws-eks::descope:aws-eks$descope:cluster$eks:index:Cluster$eks:index:VpcCni::aws-eks-sandbox-euw1-eksCluster-vpc-cni' must use an explicit provider.

i have passed explict provider and even used mergeOptions

```ts
const cluster = new eks.Cluster(
            `${name}-eksCluster`,
            {
                providerCredentialOpts: args.defaultProviders.providerCredentialOpts,
                vpcId: args.vpcId,
                subnetIds: args.vpcPrivateSubnetIds,
                nodeAssociatePublicIpAddress: false,
                skipDefaultNodeGroup: true,
                storageClasses: "gp2",
                createOidcProvider: true,
                enabledClusterLogTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"],
                version: config.eksClusterVersion,
                // the image account id is known amazon accounts for public images https://docs.aws.amazon.com/eks/latest/userguide/add-ons-images.html
                // k8s/cni compatibility:
                // https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html#vpc-cni-latest-available-version
                vpcCniOptions: {
                    initImage: `602401143452.dkr.ecr.${this.region}.amazonaws.com/amazon-k8s-cni-init:v${config.vpcCniImage}`,
                    image: `602401143452.dkr.ecr.${this.region}.amazonaws.com/amazon-k8s-cni:v${config.vpcCniImage}`,
                },
                roleMappings: [
                    ...REDACTED
                ],
                instanceRoles: [nodeRole],
                tags: tags,
            },
            pulumi.mergeOptions(opts, { parent: this, provider: args.defaultProviders.aws })
        );
```

**Comment by ami-descope** [comment] 2024-08-09 01:09
is this a regresion?

**Comment by flostadler** [comment] 2024-08-09 15:31
Hey @ami-descope, I'm sorry you're running into this! I started looking into this and found that it's not a regression, it's just a similar issue to the one listed here.

The problem is how the VPC CNI component is managed. It's implemented as a Pulumi custom resource and right now can't be configured to use an explicit provider ([see](https://github.com/pulumi/pulumi-eks/blob/4e11388203c7e87032ac9074258bdb83a5ab3b85/nodejs/eks/cni.ts#L227)).

I'm gonna open a separate issue to track this.

**Comment by flostadler** [comment] 2024-08-09 15:41
@ami-descope I opened https://github.com/pulumi/pulumi-eks/issues/1294 and added a workaround. Let's continue the discussion over there and let me know if this works for you
