### ISSUE TITLE
Consider supporting ignore_tags/key_prefixes Terraform provider option

### ISSUE THREAD

**Issue by mbergal** [pulumi/pulumi-eks#406] opened 2020-06-28 14:20 UTC
### Problem description

1. I have a VPC with subnets created by Pulumi. The subnets are tagged with some tags like stack and project names. 

2. Using Pulumi I create an EKS cluster in VPC. EKS tags subnets with  `kubernetes.io/cluster/CLUSTER_NAME` tags. All is well at this point.

3. I make a change to Pulumi VPC definition and apply it using `pulumi up`. At this point Pulimi deleted  `kubernetes.io/cluster/CLUSTER_NAME` tags and cluster is broken :(.

**Comment by metral** [comment] 2020-06-29 15:51
The tags are being removed because EKS is adding them outside of the context of Pulumi's management.

As a work around, you can leverage `transformations` to ignore the changes to the tags of VPCs and subnets and leave them in tact after EKS has added them. Here is an [example](https://github.com/pulumi/pulumi-eks/issues/271#issuecomment-548452554) that should help.

**Comment by mbergal** [comment] 2020-06-29 21:33
Sure, but then we won't be able to manage tags owned by us, `key_prefixes` would be way better, wouldn't it?

**Comment by metral** [comment] 2020-06-30 21:08
You can still add your own tags if using `ignore_changes` in the transformation, but you are correct that the management of all tags is done outside of pulumi which is not ideal.

The `key_prefixes` approach makes sense. We'll think through what a solution here would look like in Pulumi, and when we could deliver on it.

**Comment by stack72** [comment] 2022-07-27 13:25
I am going to close this out as a duplicate of #271 and add the link in there to understand that this is an option for the fix

**Closed by stack72** 2022-07-27 13:25 UTC
Labels: resolution/duplicate, kind/bug
