### ISSUE TITLE
Update pulumi-eks to build single-binary plugins

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi-eks#595] opened 2021-06-25 21:18 UTC
We should update pulumi-eks to use the same plugin-generation mechanism as what we've converted the ts boilerplate to do. https://github.com/pulumi/pulumi-component-provider-ts-boilerplate/pull/6

**Comment by stack72** [comment] 2022-07-27 13:45
Closing as a dupe of #728

**Closed by stack72** 2022-07-27 13:45 UTC
Labels: size/S, resolution/duplicate, kind/enhancement
